# Generated by Django 3.2.7 on 2021-09-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expenses_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date']},
        ),
    ]
